main: butter_smp.McPluginButters
name: McPluginButter
version: 1.1
author: Butter SMP Devs
api-version: 1.20.4
description: A plugin made for the Butter SMP
//About the mod//
commands:
  repeatkill:
    description: Repeatedly Kills Whoever you use it on.
    usage: /repeatkill
permissions:
  repeatkill.player:
    default: op
    description: Kills The Player.
//This is just what the mod does//

